spring.application.name=pricing-service

server.port=8086


# application.properties
serpapi.key=07a6a2cfa2dcedfe9c7ddb2047c00ab371a34a6057377d9274b01d17ab18e700
serpapi.enabled=true
pricing.fallback.enabled=true

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/pricing_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# URLs des services
product.service.url=http://localhost:8082
inventory.service.url=http://localhost:8083




spring.jackson.property-naming-strategy=SNAKE_CASE