server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=images
spring.cloud.gateway.routes[0].uri=http://product-service:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/uploads/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0


spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=http://product-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Route pour Auth Service
spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=http://auth-service:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
# Route pour Forecast Service
spring.cloud.gateway.routes[3].id=forecast-service
# On pointe vers le nom du conteneur Docker "forecast-service"
spring.cloud.gateway.routes[3].uri=http://forecast-service:8084
# L'URL que Postman va appeler
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/forecast/**
# On enlève "/api" avant de transmettre au backend Java (qui attend "/forecast/predict")
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# Route pour Inventory Service (GET, POST, etc.)
spring.cloud.gateway.routes[4].id=inventory-service
spring.cloud.gateway.routes[4].uri=http://inventory-service:8083
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/inventory/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

# Route pour Movements
spring.cloud.gateway.routes[5].id=movements-service
spring.cloud.gateway.routes[5].uri=http://inventory-service:8083
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/movements/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

# Route pour Alerts
spring.cloud.gateway.routes[6].id=alerts-service
spring.cloud.gateway.routes[6].uri=http://inventory-service:8083
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/alerts/**
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins[0]=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins[1]=http://localhost:4201
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders[0]=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600

jwt.secret=monSecretTresLongPourJWT256Bits123456789012345678

logging.level.org.springframework.cloud.gateway=DEBUG